title: 'UAP Report'
default_lang: pl
author:
  name: 'Grupa UAP Report'
  email: uapreportgroup@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Wiarygodne źródło informacji na temat fenomenu UAP'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
